/*Author: Dhiveshan Chetty
Purpose: A program that uses MPI to implement a global sum. A Ring pass is utilized
in order to for a process to send it's random number to the next and then each process
adds up all the random numbers so that they each have their own global sum. This
is efficient because instead of one process doing all the addition and passing,
all the processes do it simultaneously.

input: none

output: The Random values generated by processes and the sum
of the random values on each process




*/
#include <stdio.h>
#include <stdlib.h> //used for random functions
#include <mpi.h>     /* For MPI functions, etc */


int Next_higher(int my_rank, int p)
{
   return (my_rank+1)%p;
}
int Next_lower(int my_rank, int p)
{
   return (my_rank-1 +p)%p;
}

int main(void) {
   int my_rank, p, pass;

   /* Start up MPI */
   MPI_Init(NULL, NULL);

   /* Get the number of processes */
   MPI_Comm_size(MPI_COMM_WORLD, &p);

   /* Get my rank among all the processes */
   MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);
   int my_calc; // will hold the random int
   int temp;
   int global_sum; //holds the final sum for each processor
   //generates a random int
   srandom(my_rank);
   my_calc=random()%20;
   temp = global_sum= my_calc;
   //creates a destination in which to send the next value
   int dest = Next_higher(my_rank, p);
   //creates a source so the MPI_Recv can tell wwhere the value is comming from
   int src = Next_lower(my_rank,p);
   for (pass = 1; pass < p; pass++) { 
      MPI_Send(&temp,1,MPI_INT,dest,0,MPI_COMM_WORLD);
      MPI_Recv(&temp, 1, MPI_INT, src, 
         0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
      global_sum += temp;

   } 
     
   printf("Process rank: %d Process random number: %d global_sum: %d\n",my_rank,my_calc,global_sum );
   /* Shut down MPI */
   MPI_Finalize();
   return 0;
}  /* main */